# Generated by Django 5.2.10 on 2026-01-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_productimage_options_category_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('usage_limit', models.IntegerField(default=100)),
                ('uses_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_flat_rate', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('shipping_free_above', models.DecimalField(decimal_places=2, default=2000.0, max_digits=10)),
                ('tax_rate_percentage', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Miscellaneous Charges',
                'verbose_name_plural': 'Miscellaneous Charges',
            },
        ),
    ]
