# Generated by Django 5.2.10 on 2026-02-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_coupon_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='cod_extra_fee',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Extra charge for Cash on Delivery', max_digits=10),
        ),
    ]
