# Generated by Django 5.2.10 on 2026-02-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_address_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text="Admin's reason for rejecting the request", null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='return_proof_video',
            field=models.FileField(blank=True, help_text='Unboxing video proof', null=True, upload_to='returns/videos/'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_reason',
            field=models.TextField(blank=True, help_text="Customer's reason for return/exchange", null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Return Requested', 'Return Requested'), ('Return Approved', 'Return Approved'), ('Return Rejected', 'Return Rejected'), ('Returned', 'Returned'), ('Refund Initiated', 'Refund Initiated'), ('Exchange Requested', 'Exchange Requested'), ('Exchange Approved', 'Exchange Approved'), ('Exchange Rejected', 'Exchange Rejected'), ('Exchange Shipped', 'Exchange Shipped')], default='Processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Refunded', 'Refunded'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
