# Generated by Django 5.2.10 on 2026-02-02 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_rejection_reason_order_return_proof_video_and_more'),
        ('store', '0005_coupon_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='exchange_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_orders', to='store.coupon'),
        ),
    ]
