# Generated by Django 5.2.10 on 2026-02-02 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_orderitem_admin_comment_and_more'),
        ('store', '0005_coupon_siteconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='exchange_coupon',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='order',
            name='return_proof_video',
        ),
        migrations.RemoveField(
            model_name='order',
            name='return_reason',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='exchange_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.coupon'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_proof_video',
            field=models.FileField(blank=True, null=True, upload_to='returns/videos/'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Return Requested', 'Return Requested'), ('Return Approved', 'Return Approved'), ('Return Rejected', 'Return Rejected'), ('Returned', 'Returned'), ('Exchange Requested', 'Exchange Requested'), ('Exchange Approved', 'Exchange Approved'), ('Exchange Rejected', 'Exchange Rejected'), ('Exchanged', 'Exchanged')], default='Ordered', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Processing', max_length=30),
        ),
    ]
