# Generated by Django 5.2.10 on 2026-02-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_exchange_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Online', 'Online (Razorpay)'), ('COD', 'Cash on Delivery')], default='Online', max_length=10),
        ),
    ]
