# Generated by Django 5.2.10 on 2026-02-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_link',
            field=models.URLField(blank=True, help_text='Paste shipment tracking URL here', max_length=500, null=True),
        ),
    ]
